name: Feature Development Workflow

on:
  push:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'
  
      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Run PHPUnit Tests
        id: phpunit
        run: ./vendor/bin/phpunit 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  merge-to-main:
    runs-on: ubuntu-latest
    needs: [build_test]
    if: success() && contains(github.ref, 'test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set Git config
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "Github Actions"

      - name: Merge test to main
        run: |
            git fetch --unshallow
            git checkout main
            git pull
            git merge --no-ff test -m "Auto-merge test to main"
            git push

  deploy-to-prod:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    needs: [build_test, merge-to-main]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App - Production'
        id: deploy-to-webapp  
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SWE40006-Web-App'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: .