name: Feature Development Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tests should be run
        run: |
            if [[ $GITHUB_REF == "refs/heads/test" || $GITHUB_REF == "refs/heads/main" ]]; then
                echo "Tests will be run for this branch."
            else
                echo "No tests will be run for this branch."
                exit 0
            fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        run: |
          if [ -f composer.json ]; then
            echo "composer.json found"
            echo "files_exists=true" >> $GITHUB_ENV
          else
            echo "composer.json not found"
            echo "files_exists=false" >> $GITHUB_ENV
          fi
        
      - name: Install Composer Dependencies
        if: env.files_exists == 'true'
        run: composer install
        
      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit

  merge-to-main:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/pull/') && github.event.action == 'synchronize'
    steps:
      - name: Merge Test Branch into Main
        run: |
          # Merge the test branch into the main branch
          git checkout main
          git pull origin main
          git merge --no-ff $GITHUB_HEAD_REF
          git push origin main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'SWE40006-Web-App'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A431B0A89C94D4FBBD9CE57849F8B38 }}
          package: .
        