name: Feature Development Workflow

on:
  push:

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'
  
      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Run PHPUnit Tests
        id: phpunit
        run: ./vendor/bin/phpunit 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  deploy-to-test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'test')
    needs: build_test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App - Test'
        uses: azure/webapps-deploy@v2
        id: deploy-to-test-webapp
        with:
          app-name: 'SWE40006-Web-App-Test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST  }}
          package: .

  merge-to-main:
    runs-on: ubuntu-latest
    needs: [build_test, deploy-to-test]
    if: success() && contains(github.ref, 'test')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: 'main'
      
      - name: Merge Test Branch into Main
        run: |
          git fetch origin main
          git checkout main
          git merge test
          git push origin main

  deploy-to-prod:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'main')
    needs: [build_test, merge-to-main]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App - Production'
        id: deploy-to-webapp  
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SWE40006-Web-App'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: .