name: Feature Development Workflow

on:
  push:
    branches:
      - 'test'

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'
  
      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Run PHPUnit Tests
        id: phpunit
        run: ./vendor/bin/phpunit

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build_test

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App - Test'
        uses: azure/webapps-deploy@v2
        id: deploy-to-test-webapp
        with:
          app-name: 'SWE40006-Web-App-Test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_TEST  }}
          package: .

      - name: 'Deploy to Azure Web App - Production'
        if: ${{ needs.build_test.result == 'success' }}
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'SWE40006-Web-App'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
          package: .
        

      - name: Merge Code to Main
        if: ${{ needs.build_test.result == 'success' }}
        run: |
          # Configure Git with user information
          git config --global user.email "aligoose.martin@gmail.com"
          git config --global user.name "AliGoose"

          # Clone the repository
          git clone https://github.com/AliGoose/SWE40006-Web-App.git

          # Change to the repository directory
          cd SWE40006-Web-App

          # Checkout the 'main' branch
          git checkout main

          # Merge 'test' into 'main'
          git merge origin/test

          # Push the changes to 'main'
          git push

          # Clean up
          cd ..
          rm -rf SWE40006-Web-App