name: Feature Development Workflow

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tests should be run
        run: |
            if [[ $GITHUB_REF == "refs/heads/test" || $GITHUB_REF == "refs/heads/main" ]]; then
                echo "Tests will be run for this branch."
            else
                echo "No tests will be run for this branch."
                exit 0
            fi

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  merge-to-test:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/pull/') && github.event.action == 'synchronize'
    steps:
      - name: Merge Feature Branch into Test
        run: |
          # Merge the feature branch into the test branch
          git checkout test
          git pull origin test
          git merge --no-ff $GITHUB_HEAD_REF
          git push origin test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'SWE40006-Web-App-Test'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C58CC9932967434BAFD03C015DDB4A49 }}
          package: .